version: "3"
services:

  nginx:
    image: nginx:stable-alpine
    ports:
      - "4000:80" # exposing the nginx container on port 4000,  --> port 80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - node-app
  node-app:
    build: .
    environment:
      - PORT=4000
    depends_on: #node is dependent on mongo , start after mongo container is up
      - mongo
      - redis
  mongo:
    image: mongo
    volumes:      #specifies the volumes . its an anonimous volume named mongo-db
      - mongo-db:/data/db
  redis:
    image: redis
volumes:
  mongo-db:
  