version: "3"
services:
  nginx:
    ports:
      - "4000:80"
  node-app:
    build: 
      context: .
      args: 
        NODE_ENV: development
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_PASSWORD=Test1234
      - MONGO_USER=mongoAdmin
      - SESSION_SECRET=123456
    command: npm start
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoAdmin
      - MONGO_INITDB_ROOT_PASSWORD=Test1234