version: "3"
services:
  node-app:
    build: .
    ports:
      - "3000:4000"
    environment:
      - PORT=4000
  mongo:
    image: mongo
    volumes:
      - mongo-db:/data/db

volumes:
  mongo-db:
  