version: "3"
services:
  node-app:
    build: .
    ports:
      - "3000:4000"
    environment:
      - PORT=4000
    depends_on: #node is dependent on mongo , start after mongo container is up
      - mongo
      - redis
  mongo:
    image: mongo
    volumes:      #specifies the volumes . its an anonimous volume named mongo-db
      - mongo-db:/data/db
  redis:
    image: redis
volumes:
  mongo-db:
  