version: "3"
services:
  node-app:
    build: .
    ports:
      - "3000:4000"
    environment:
      - PORT=4000
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoAdmin
      - MONGO_INITDB_ROOT_PASSWORD=Test@1234
    volumes:
      - mongo-db:/data/db

volumes:
  mongo-db:
  